import Link from "next/link"

export const metadata = { title: "Privacy Policy — RelaunchJobs" }

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100vh", backgroundColor: "#fff", padding: "60px 5%" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto" }}>
        <div style={{ display: "flex", gap: "20px", marginBottom: "32px", flexWrap: "wrap" }}>
          <Link href="/" style={{ fontSize: "14px", color: "#1a3a6b", textDecoration: "none" }}>← Back to RelaunchJobs</Link>
          <Link href="/terms" style={{ fontSize: "14px", color: "#6b7280", textDecoration: "none" }}>Terms</Link>
          <Link href="/contact" style={{ fontSize: "14px", color: "#6b7280", textDecoration: "none" }}>Contact</Link>
        </div>

        <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: "36px", color: "#0f172a", marginBottom: "8px" }}>
          Privacy Policy
        </h1>
        <p style={{ color: "#6b7280", fontSize: "14px", marginBottom: "8px" }}>
          Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </p>
        <div style={{ display: "inline-block", background: "#e8f5ef", color: "#1a6b4a", borderRadius: "20px", padding: "5px 14px", fontSize: "13px", fontWeight: 600, marginBottom: "40px" }}>
          ✓ We never sell your data — ever.
        </div>

        {[
          {
            title: "1. What We Collect",
            body: "We collect your email address, the career information you provide during intake (job title, industry, years of experience, context), and the outputs generated by the AI pipeline. We also collect standard usage data (page views, feature usage) to improve the service.",
          },
          {
            title: "2. How We Use Your Data",
            body: "Your data is used solely to generate your career analysis, power the AI pipeline, and communicate with you about your account. We do not use your data to train AI models without explicit consent. We do not use your data for advertising.",
          },
          {
            title: "3. We Never Sell Your Data",
            body: "We do not sell, rent, or trade your personal information to any third party, ever. Your career history is sensitive — we treat it that way.",
          },
          {
            title: "4. Data Storage & Security",
            body: "Your data is stored in Supabase (a SOC 2 Type II certified platform) with row-level security. Connections are encrypted in transit (TLS 1.2+). We use industry-standard practices to protect your information.",
          },
          {
            title: "5. Third-Party Services",
            body: "We use the following third parties to operate the service: Supabase (database and authentication), Anthropic (AI processing — career data is sent to Claude for analysis), Resend (transactional email), and Vercel (hosting). Each has their own privacy policy.",
          },
          {
            title: "6. Your Rights",
            body: "You can request a copy of your data, ask us to delete your account and all associated data, or opt out of any communications at any time. Email support@relaunchjobs.app and we will respond within 48 hours.",
          },
          {
            title: "7. Cookies",
            body: "We use only essential cookies required for authentication. We do not use tracking cookies or third-party advertising cookies.",
          },
          {
            title: "8. Children's Privacy",
            body: "RelaunchJobs is not directed to children under 18. We do not knowingly collect data from minors.",
          },
          {
            title: "9. Changes to This Policy",
            body: "If we make material changes to this policy, we will notify you by email before the changes take effect.",
          },
          {
            title: "10. Contact",
            body: "For privacy questions or data requests, contact us at support@relaunchjobs.app.",
          },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: "32px" }}>
            <h2 style={{ fontSize: "18px", fontWeight: 700, color: "#1a3a6b", marginBottom: "10px" }}>
              {section.title}
            </h2>
            <p style={{ fontSize: "15px", lineHeight: 1.75, color: "#4a5568" }}>{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
